import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Vercel OG</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:title" content="Vercel OG" />
        <meta
          property="og:description"
          content="Generated by create next app"
        />
        <meta property="og:image" content="http://localhost:3000/api/og" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p>Dynamic OG Generator Test</p>
      </main>
    </div>
  );
}
